__author__ = 'ali'

lead_fields_list = {
    'id' : 'Lead ID',
    'title' : 'Title',
    'salutation' : 'Salutation',
    'first_name' : 'First Name',
    'last_name' : 'Last Name',
    'full_name' : 'Full Name',
    'ip_address_c' : 'IP Address',
    'keywords_c' : 'KEYWORDS',
    'lead_source' : 'Lead Source',
    'hubspot_found_site_via_c' : 'Found Site Via',
    'campaign_c' : 'Lead Campaign',
    'gclid_c' : 'gclid',
    'first_referrer_c' : 'First Referrer',
    'first_page_viewed_c' : 'First Page Viewed',
    'hubspot_first_visit_c' : 'First Visit',
    'hubspot_guid_c' : 'HubSpot GUID',
    'opportunity_id' : 'OPP_ID',
    'status' : 'Status',
    'primary_address_country' : 'Primary_Address_Country',
    'primary_address_city' : 'Primary Address City',
    'producttype_c' : 'Product_Type_LEAD',
    'originally_assigned_to_c' : 'Originally_Assigned_to',
    'assigned_user_name' : 'Assigned to',
    'user_id_c' : 'User_Name',
    'couldnt_contact_noofattempts_c' : 'Couldnt Contact- No of Attempts',
    'number_of_visits_c' : 'number of visits',
    'email1' : 'Email Address',
    'bounced_email_c' : 'Bounced Email',
    'emails_opened_c' : 'Emails Opened',
    'emails_clicked_c' : 'Emails Clicked',
    'opted_out_of_email_c' : 'opted out of email',
    'phone_work' : 'Office Phone',
    'phone_mobile' : 'Mobile',
    'no_of_email_boxes_c' : 'no of email boxes',
    'no_of_employees_c' : 'No of Employees',
    'twitter' : 'Twitter',
    'website' : 'Website',
    'unsubscribe_frank_email_c' : 'unsubscribe frank email',
    'cf_reseller_leads_name' : 'Reseller_Name',
    'date_modified' : 'Date_Modified',
    'date_entered' : 'Date_Created',
}

opportunity_fields_list = {
    'date_entered' : 'Date_Created',
    'date_modified' : 'Date_Modified',
    'cf_reseller_leads_name' : 'Reseller_Name',
    'date_closed' : 'Expected_Close_Date',
    'product_type_c' : 'Product_Type_OPP',
    'enduser_name_c' : 'User_Name_OPP',
    'sales_stage' : 'Sales_Stage',
    'no_years_c' : 'No of Years',
    'amount' : 'Amount_USD',
    'email_c' : 'Email',
    'billing_address_country_c' : 'Billing_Address_Country',
    'cf_reseller_opportunities_name' : 'Reseller_Name_OPP',
    'hubspot_number_conversion_c' : 'No. of Conversion Events',
    'hubspot_first_conversion_event_c' : 'First Conversion Event',
    'hubspot_first_conversion_date_c' : 'First Conversion Date',
    'hubspot_recent_cv_event_c' : 'Recent Conversion Event',
    'hubspot_recent_conversion_date_c' : 'Recent Conversion Date',
    'license_number_c' : 'license Number',
}

